# We have to pass `sources`, so minimize the number of files that are scanned
sources:
  - ../templates
templates:
  - ../templates/AppSecrets.stencil
output:
  ../../Inventory/Application
args:
  base_url: ${BASE_URL}
  keychain_service: ${KEYCHAIN_SERVICE}
  logger_app_id: ${LOGGER_APP_ID}
  logger_app_secret: ${LOGGER_APP_SECRET}
  logger_encryption_key: ${LOGGER_ENCRYPTION_KEY}
